import mod from "../lib/string.js";

export default mod;
export const StringNumber = mod.StringNumber;
export const ansi = mod.ansi;
export const camelCaseToDash = mod.camelCaseToDash;
export const camelCaseToDashed = mod.camelCaseToDashed;
export const camelCaseToSeparated = mod.camelCaseToSeparated;
export const createFormatter = mod.createFormatter;
export const createMarkup = mod.createMarkup;
export const escape = mod.escape;
export const format = mod.format;
export const formatMethod = mod.formatMethod;
export const fuzzy = mod.fuzzy;
export const inspect = mod.inspect;
export const inspectError = mod.inspectError;
export const inspectStack = mod.inspectStack;
export const latinize = mod.latinize;
export const markup = mod.markup;
export const markupMethod = mod.markupMethod;
export const naturalSort = mod.naturalSort;
export const occurrenceCount = mod.occurrenceCount;
export const regexp = mod.regexp;
export const resize = mod.resize;
export const stripMarkup = mod.stripMarkup;
export const toCamelCase = mod.toCamelCase;
export const toTitleCase = mod.toTitleCase;
export const unicode = mod.unicode;
export const wordwrap = mod.wordwrap;
